# Generated by Django 2.2.27 on 2022-09-20 18:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_api', '0002_auto_20220919_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='OrderedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество товаров в заказе')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stripe_api.Item', verbose_name='Товар')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stripe_api.Order', verbose_name='Заказ')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='item',
            field=models.ManyToManyField(through='stripe_api.OrderedItem', to='stripe_api.Item', verbose_name='Товар'),
        ),
    ]
