version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env
  stripe:
    image: thisispetrovich/test_stripe:v0.8
    restart: always
    volumes:
      - static_value:/app/test_rishat/static/
    depends_on:
      - db
    env_file:
      - ./.env 
  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
    depends_on:
      - stripe

volumes:
  static_value:
 